from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblkq = QtWidgets.QLabel(self.centralwidget)
        self.lblkq.setGeometry(QtCore.QRect(10, 10, 341, 100))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lblkq.setFont(font)
        self.lblkq.setFrameShape(QtWidgets.QFrame.Box)
        self.lblkq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblkq.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblkq.setObjectName("lblkq")
        self.btn_percet = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("%"))
        self.btn_percet.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_percet.setFont(font)
        self.btn_percet.setObjectName("btn_percet")
        self.btn_c = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("c"))
        self.btn_c.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_c.setFont(font)
        self.btn_c.setObjectName("btn_c")
        self.btnero = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.remove_it())
        self.btnero.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btnero.setFont(font)
        self.btnero.setObjectName("btnero")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("/"))
        self.btn_div.setGeometry(QtCore.QRect(275, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_div.setFont(font)
        self.btn_div.setObjectName("btn_div")
        self.btn_mul = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("*"))
        self.btn_mul.setGeometry(QtCore.QRect(275, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_mul.setFont(font)
        self.btn_mul.setObjectName("btn_mul")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("7"))
        self.btn_7.setGeometry(QtCore.QRect(10, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_7.setFont(font)
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("8"))
        self.btn_8.setGeometry(QtCore.QRect(100, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_8.setFont(font)
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("9"))
        self.btn_9.setGeometry(QtCore.QRect(190, 190, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_9.setFont(font)
        self.btn_9.setObjectName("btn_9")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("-"))
        self.btn_minus.setGeometry(QtCore.QRect(275, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_minus.setFont(font)
        self.btn_minus.setObjectName("btn_minus")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("4"))
        self.btn_4.setGeometry(QtCore.QRect(10, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_4.setFont(font)
        self.btn_4.setObjectName("btn_4", )
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("5"))
        self.btn_5.setGeometry(QtCore.QRect(100, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_5.setFont(font)
        self.btn_5.setObjectName("btn_5")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("6"))
        self.btn_6.setGeometry(QtCore.QRect(190, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_6.setFont(font)
        self.btn_6.setObjectName("btn_6")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("+"))
        self.btn_add.setGeometry(QtCore.QRect(275, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName("btn_add")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("3"))
        self.btn_3.setGeometry(QtCore.QRect(190, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("1"))
        self.btn_1.setGeometry(QtCore.QRect(10, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_1.setFont(font)
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("2"))
        self.btn_2.setGeometry(QtCore.QRect(100, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.match_it())
        self.btn_equal.setGeometry(QtCore.QRect(275, 440, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_equal.setFont(font)
        self.btn_equal.setObjectName("btn_equal")
        self.btn_add_minus = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.plus_minus_it())
        self.btn_add_minus.setGeometry(QtCore.QRect(10, 440, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_add_minus.setFont(font)
        self.btn_add_minus.setObjectName("btn_add_minus")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it('0'))
        self.btn_0.setGeometry(QtCore.QRect(100, 440, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_0.setFont(font)
        self.btn_0.setObjectName("btn_0")
        self.btn_decimal = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.dot_it())
        self.btn_decimal.setGeometry(QtCore.QRect(190, 440, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.btn_decimal.setFont(font)
        self.btn_decimal.setObjectName("btn_decimal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def dot_it(self):
        screen = self.lblkq.text()
        if screen[-1] == '.':
            pass
        else:
            self.lblkq.setText(f'{self.lblkq.text()}.')

    def remove_it(self):
        screen = self.lblkq.text()
        # Remove last item in list/string
        screen = screen[:-1]
        # Out out back to the screen
        self.lblkq.setText(screen)

    # Change from positive/negative
    def plus_minus_it(self):
        screen = self.lblkq.text()
        if '-' in screen:
            self.lblkq.setText(screen.replace('-', ''))
        else:
            self.lblkq.setText(f'-{screen}')

    def match_it(self):
        screen = self.lblkq.text()
        # Do the match
        answer = eval(screen)
        # out put the 
        self.lblkq.setText(str(answer))

    def press_it(self, pressed):
        if pressed == "c":
            self.lblkq.setText('0')
        else:
            if self.lblkq.text() == '0':
                self.lblkq.setText("")
            self.lblkq.setText(f'{self.lblkq.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.lblkq.setText(_translate("MainWindow", "0"))
        self.btn_percet.setText(_translate("MainWindow", "%"))
        self.btn_c.setText(_translate("MainWindow", "C"))
        self.btnero.setText(_translate("MainWindow", "<<"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_mul.setText(_translate("MainWindow", "*"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_add_minus.setText(_translate("MainWindow", "+/-"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_decimal.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
